# Generated by Django 2.1.9 on 2021-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'credit'), ('DEBIT', 'debit')], default='CREDIT', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('DECLINED', 'declined'), ('COMPLETED', 'completed')], max_length=9),
        ),
    ]
