# Generated by Django 2.2 on 2021-06-06 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
