# Generated by Django 2.1.9 on 2021-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BANK_TRANSACTION', 'Bank Transaction'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('PEER_TO_PEER', 'Peer To Peer')], help_text='type of transaction performed', max_length=100, null=True),
        ),
    ]
