# Generated by Django 2.1.9 on 2021-06-06 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2ptransfer',
            old_name='receipient',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='new_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
