# Generated by Django 2.1.9 on 2021-06-06 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('FIXED', 'Fixed'), ('CURRENT', 'Current'), ('SAVINGS', 'Savings')], max_length=50)),
                ('account_balance', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.RemoveField(
            model_name='balance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.DeleteModel(
            name='NewUserPhoneVerification',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='Phonenumber',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='new_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_action',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer')], editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_journal',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCLED', 'Cancled')], default='PENDING', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AllBanks',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankTransfer',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='P2PTransfer',
        ),
    ]
