# Generated by Django 2.1.9 on 2021-06-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
        migrations.DeleteModel(
            name='AllBanks',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankTransfer',
        ),
        migrations.DeleteModel(
            name='P2PTransfer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
