# Generated by Django 2.2 on 2021-06-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210606_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account_balance',
        ),
    ]
