# Generated by Django 2.1.9 on 2021-06-07 01:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210605_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('created',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('book_balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
