# Generated by Django 3.2.16 on 2024-05-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbanks',
            name='created',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='newuserphoneverification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='created',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
    ]
