# Generated by Django 2.1.9 on 2021-06-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210606_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'created_on'},
        ),
    ]
