# Generated by Django 2.1.9 on 2021-06-07 18:16

from django.db import migrations, models
import flite.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210607_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default=flite.users.utils.TransactionStatus('Successful'), help_text='status of transaction performed', max_length=200),
        ),
    ]
