# Generated by Django 2.1.9 on 2021-06-06 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210606_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allbanks',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='newuserphoneverification',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='modified',
            new_name='modified_on',
        ),
        migrations.RemoveField(
            model_name='allbanks',
            name='created',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='newuserphoneverification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='created',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
        migrations.AddField(
            model_name='allbanks',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuserphoneverification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
