# Generated by Django 2.1.9 on 2021-06-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='owner',
        ),
        migrations.DeleteModel(name='Balance', ),
    ]
