# Generated by Django 2.1.9 on 2021-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210608_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Bank Transaction', 'BANK_TRANSACTION'), ('Deposit', 'DEPOSIT'), ('Withdraw', 'WITHDRAW'), ('Peer To Peer', 'PEER_TO_PEER'), ('Peer To Peer (Debit)', 'PEER_TO_PEER_DEBIT'), ('Peer To Peer (Credit)', 'PEER_TO_PEER_CREDIT')], help_text='type of transaction performed', max_length=100, null=True),
        ),
    ]
