# Generated by Django 2.1.9 on 2021-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='transaction_type',
            field=models.CharField(default='credit', max_length=200),
        ),
    ]
