# Generated by Django 2.1.9 on 2021-06-07 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBanks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'All Banks',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AllBanks')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('authorization_code', models.CharField(max_length=200)),
                ('ctype', models.CharField(max_length=200)),
                ('cbin', models.CharField(default=None, max_length=200)),
                ('cbrand', models.CharField(default=None, max_length=200)),
                ('country_code', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('expiry_month', models.CharField(help_text='MM', max_length=2)),
                ('expiry_year', models.CharField(help_text='YYYY', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('reference', models.CharField(default='OrVytkXBpO', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=9)),
                ('trans_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], default='Incoming', max_length=8)),
                ('amount', models.FloatField(default=0.0)),
                ('charge', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Transaction')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Bank')),
            ],
            options={
                'verbose_name_plural': 'Bank Transfers',
            },
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Transaction')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Card')),
            ],
            options={
                'verbose_name_plural': 'Card Transfers',
            },
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='P2PTransfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Transaction')),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'P2P Transfers',
            },
            bases=('account.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction_related', related_query_name='account_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
