# Generated by Django 2.1.9 on 2021-06-08 03:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import flite.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBanks',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('created',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Approved Bank',
                'verbose_name_plural': 'Approved Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number',
                 models.CharField(
                     max_length=50,
                     validators=[flite.account.models.verify_number])),
                ('account_type',
                 models.CharField(choices=[('Savings', 'Savings'),
                                           ('Current', 'Current'),
                                           ('Corporate', 'Corporate'),
                                           ('Joint', 'Joint')],
                                  default='Savings',
                                  max_length=50)),
                ('bank',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='account.AllBanks')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('created',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('authorization_code', models.CharField(max_length=200)),
                ('ctype', models.CharField(max_length=200)),
                ('cbin', models.CharField(max_length=200, null=True)),
                ('cbrand', models.CharField(max_length=200, null=True)),
                ('country_code', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('number',
                 models.CharField(
                     max_length=200,
                     validators=[flite.account.models.verify_number])),
                ('bank', models.CharField(max_length=200)),
                ('expiry_month',
                 models.CharField(
                     help_text='MM',
                     max_length=2,
                     validators=[flite.account.models.verify_number])),
                ('expiry_year',
                 models.CharField(
                     help_text='YYYY',
                     max_length=4,
                     validators=[flite.account.models.verify_number])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('created',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status',
                 models.CharField(choices=[('Pending', 'Pending'),
                                           ('Successful', 'Successful'),
                                           ('Cancelled', 'Cancelled'),
                                           ('Rejected', 'Rejected')],
                                  default='Successful',
                                  max_length=9)),
                ('trans_type',
                 models.CharField(choices=[('Deposit', 'Deposit'),
                                           ('Withdraw', 'Withdraw'),
                                           ('Transfer', 'Transfer')],
                                  default='Deposit',
                                  max_length=8)),
                ('category',
                 models.CharField(choices=[('Credit', 'Credit'),
                                           ('Debit', 'Debit')],
                                  default='Credit',
                                  max_length=6)),
                ('amount', models.FloatField(default=0.0)),
                ('charge', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=12)),
                ('is_utilized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('transaction_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='account.Transaction')),
                ('bank',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='account.Bank')),
            ],
            options={
                'verbose_name_plural': 'Bank Transfers',
            },
            bases=('account.transaction', ),
        ),
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('transaction_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='account.Transaction')),
                ('card',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='account.Card')),
            ],
            options={
                'verbose_name_plural': 'Card Transfers',
            },
            bases=('account.transaction', ),
        ),
        migrations.CreateModel(
            name='P2PTransfer',
            fields=[
                ('transaction_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='account.Transaction')),
                ('receipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='recipient',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'P2P Transfers',
            },
            bases=('account.transaction', ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
