# Generated by Django 2.1.9 on 2021-06-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='7shhLIBnw5', max_length=10, unique=True),
        ),
    ]
