# Generated by Django 2.1.9 on 2021-06-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_utilized',
        ),
    ]
