# Generated by Django 2.1.9 on 2021-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210607_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allbanks',
            options={'ordering': ['name'], 'verbose_name': 'Approved Bank', 'verbose_name_plural': 'Approved Banks'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['account_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='card',
            name='cbin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cbrand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='country_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='KbM3zliaCP', max_length=10, unique=True),
        ),
    ]
