# Generated by Django 2.1.9 on 2021-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_transaction_is_utilized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Successful', max_length=10),
        ),
    ]
