# Generated by Django 2.1.9 on 2021-06-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2ptransfer',
            name='receipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipient',
                to='account.Account'),
        ),
    ]
