# Generated by Django 2.1.9 on 2021-06-08 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
